### ISSUE TITLE
Feature: ORed Matchers

### ISSUE THREAD

**Issue by dariozachow** [crossplane-contrib/function-status-transformer#26]
### What problem are you facing?

I have a composite resource containing `spec.users: ["user1", "user2"]` For each user in the list a Managed Resource "Role" will be created. Each Role can throw an error if the username is spelled incorrectly. Thus user1 has the ReconcileError and user2 does not lead to an error. In my case I want to match the error and if one of the Roles has this error show it in the claim.
I started of with the following matching rule, which works fine if both users are incorrect. But if one of them is not correctly spelled the error ist not shown.

```yaml
apiVersion: function-status-transformer.fn.crossplane.io/v1beta1
kind: StatusTransformation
statusConditionHooks:
  - matchers:
      - resources:
          - name: .*
        conditions:
          - type: Synced
            status: 'False'
            reason: ReconcileError
            message: .*
    setConditions:
      - target: CompositeAndClaim
        condition:
          type: RoleReady
          status: 'False'
          reason: FailedToCreate
          message: User "user1" is not known

```

### How could this Function help solve your problem?

It would be awesome to have the ability to OR match conditions
