### ISSUE TITLE
Propagate composite resource status to claim

### ISSUE THREAD

**Issue by ashishkurian** [crossplane-contrib/function-status-transformer#36]
### What problem are you facing?
Is there a way to propagate the status conditions of the composite resource back to the claim? At the moment we can only propagate it from the managed/composed resource back to the claim and composite

### How could this Function help solve your problem?
In the status transformer function we can only set target as CompositeAndClaim. If we can develop a way to watch for errors on the composite resource and propagate to the claim, that means the claim can itself report all the errors happening in the resource chain.

### Example scenario

In the below composition, I injected an error at the tags field. This triggered an error at the composite resource level and thus did not proceed to create the composed resource. In the claim, the status conditions only showed it is waiting for composite resource to be ready. On the other hand, the composite resource had a status condition that it failed due to missing schema.

```yaml
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xawsassumerole.mycompany.com
spec:
  compositeTypeRef:
    apiVersion: mycompany.com/v1alpha1
    kind: XAwsAssumeRole
  environment:
    environmentConfigs:
    - type: Reference
      ref:
        name: iaws-main
    - type: Reference
      ref:
        name: iaws-auto
  mode: Pipeline
  pipeline:
    - step: aws-assumerole-policies
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            {{- $environmentConfigs := (index .context "apiextensions.crossplane.io/environment") }}
            {{- $eksClusterName := (index $environmentConfigs "eksClusterName") }}
            {{- $accountId := (index $environmentConfigs "accountId") }}
            # {{- $deletionPolicy := .observed.composite.resource.spec.crossplaneParameters.deletionPolicy }}
            {{- $deletionPolicy := "Delete" }}
            {{- $region := (index $environmentConfigs "region") }}
            {{- $HubAccountId := (index $environmentConfigs "hubAccountId") }}
            {{- $providerConfigRef := "providerconfig-aws" }}
            {{- $claimName := (index .observed.composite.resource.metadata.labels "crossplane.io/claim-name") }}
            ---
            apiVersion: iam.aws.crossplane.io/v1beta1
            kind: Policy
            metadata:
              name: aws-assmrolepolicy-restricted-ashtest
              labels:
                resource: aws-assumerolepolicy-restricted-ashtest
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: Policy-AssmRoleInlineRestrictedAshtest
            spec:
              deletionPolicy: {{$deletionPolicy}}
              providerConfigRef:
                name: {{$providerConfigRef}}
              forProvider:
                name: aws-assmrolepolicy-restricted-ashtest
                document: |
                  {
                    "Version": "2012-10-17",
                    "Statement": [
                      {
                        "Sid": "RunInstancesTagRestriction",
                        "Effect": "Allow",
                        "Action": "ec2:RunInstances",
                        "Resource": [
                          "arn:aws:ec2:{{$region}}:{{$accountId}}:instance/*"
                        ],
                        "Condition": {
                          "StringEquals": {
                            "aws:RequestTag/kubernetes.io/cluster/{{$eksClusterName}}" : "owned"
                          }
                        }
                      },
                      {
                        "Sid": "RunInstancesVpcRestriction",
                        "Effect": "Allow",
                        "Action": "ec2:RunInstances",
                        "Resource": "arn:aws:ec2:{{$region}}:{{$HubAccountId}}:subnet/*"
                      },
                      {
                        "Sid": "InstanceActionsTagRestriction",
                        "Effect": "Allow",
                        "Action": [
                          "ec2:TerminateInstances",
                          "ec2:StartInstances",
                          "ec2:StopInstances",
                          "ec2:CreateTags"
                        ],
                        "Resource": "arn:aws:ec2:{{$region}}:{{$accountId}}:instance/*",
                        "Condition": {
                          "StringEquals": {
                            "ec2:ResourceTag/kubernetes.io/cluster/{{$eksClusterName}}": [
                              "owned",
                              "shared"
                            ]
                          }
                        }
                      },
                      {
                        "Sid": "AutoscalingActionsTagRestriction",
                        "Effect": "Allow",
                        "Action": [
                          "autoscaling:UpdateAutoScalingGroup",
                          "autoscaling:SuspendProcesses",
                          "autoscaling:ResumeProcesses",
                          "autoscaling:TerminateInstanceInAutoScalingGroup"
                        ],
                        "Resource": "arn:aws:autoscaling:{{$region}}:{{$accountId}}:autoScalingGroup:*:autoScalingGroupName/*",
                        "Condition": {
                          "StringEquals": {
                            "autoscaling:ResourceTag/kubernetes.io/cluster/{{$eksClusterName}}":[
                              "owned",
                              "shared"
                            ]
                          }
                        }
                      },
                      {
                        "Sid": "EKS",
                        "Effect": "Allow",
                        "Action": [
                          "eks:Describe*",
                          "eks:List*"
                        ],
                        "Resource": [
                          "arn:aws:eks:{{$region}}:{{$accountId}}:cluster/{{$eksClusterName}}",
                          "arn:aws:eks:{{$region}}:{{$accountId}}:nodegroup/{{$eksClusterName}}/*/*"
                        ]
                      },
                      {
                        "Sid": "EC2DescribeRegion",
                        "Action": "ec2:DescribeRegions",
                        "Effect": "Allow",
                        "Resource": "*"
                      }
                    ]
                  }
                tags:
                  - key: claim-name
                    value: {{$claimName}}
                  - key: created-by
                    value: crossplane
                  - key: composition-name
                    value: XFullAccess
                  - keyss: composition-name
                    valuesss: XFullAccess
    

    - step: status-population
      functionRef:
        name: function-status-transformer
      input:
        apiVersion: function-status-transformer.fn.crossplane.io/v1beta1
        kind: StatusTransformation
        statusConditionHooks:

        - matchers:
          - resources:
            - name: "Policy-*"
            conditions:
            - type: Ready
              status: "True"
              reason: Available
          setConditions:
          - target: CompositeAndClaim
            condition:
              type: AssumeRolePolicyReady
              status: "True"
              reason: AssumeRolePolicyReady
              message: "Successfully created the policy for the aws assume role"
        
        - matchers:
          - resources:
            - name: "Policy-*"
            conditions:
            - type: Synced
              status: "False"
              reason: ReconcileError
              message: "(?P<Error>.*)"
          setConditions:
          - target: CompositeAndClaim
            force: true
            condition:
              type: AssumeRolePolicyReady
              status: "False"
              reason: FailedToCreate
              message: "Error: {{ .Error }}"

    # - step: claim-resource-info
    #   functionRef:
    #     name: function-go-templating
    #   input:
    #     apiVersion: gotemplating.fn.crossplane.io/v1beta1
    #     kind: GoTemplate
    #     source: Inline
    #     inline:
    #       template: |
    #         {{ $AwsAssumeRoleArn := get .observed.resources.<populate this later>.resource.status.atProvider "arn" | default dict }}
    #         ---
    #         apiVersion: mycompany.com/v1alpha1
    #         kind: XAwsAssumeRole
    #         status:
    #           AwsAssumeRole:
    #             arn: {{ $AwsAssumeRoleArn }}  

    - step: automatically-detect-ready-composed-resources
      functionRef:
        name: function-auto-ready
    
    - step: sequence-creation
      functionRef:
        name: function-sequencer
      input:
        apiVersion: sequencer.fn.crossplane.io/v1beta1
        kind: Input
        rules:
          - sequence:
            - Policy-*
```

**Comment by ashishkurian** [comment]
I found this section https://github.com/crossplane-contrib/function-status-transformer?tab=readme-ov-file#matching-the-composite-resource. 

However, I still cannot make it work. I have simplified my composition for easier debugging.

```yaml
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xawsassumerole.mycompany.com
spec:
  compositeTypeRef:
    apiVersion: mycompany.com/v1alpha1
    kind: XAwsAssumeRole
  environment:
    environmentConfigs:
    - type: Reference
      ref:
        name: iaws-main
    - type: Reference
      ref:
        name: iaws-auto
  mode: Pipeline
  pipeline:
    - step: aws-assumerole-policies
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            {{- $deletionPolicy := "Delete" }}
            {{- $providerConfigRef := "providerconfig-aws" }}
            {{- $claimName := (index .observed.composite.resource.metadata.labels "crossplane.io/claim-name") }}
            ---
            apiVersion: iam.aws.crossplane.io/v1beta1
            kind: Policy
            metadata:
              name: firstpolicy
              labels:
                resource: firstpolicy
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: Policy-FirstPolicy
            spec:
              deletionPolicy: {{$deletionPolicy}}
              providerConfigRef:
                name: {{$providerConfigRef}}
              forProvider:
                name: firstpolicy
                document: |
                  {
                    "Version": "2012-10-17",
                    "Statement": [
                      {
                        "Sid": "EC2DescribeRegion",
                        "Action": "ec2:DescribeRegions",
                        "Effect": "Allow",
                        "Resource": "*"
                      }
                    ]
                  }
                tags:
                  - key: claim-name
                    value: {{$claimName}}
                  - key: created-by
                    value: crossplane
                  - keyssssssssssssssssssssssssss: composition-name
                    valuessssssssssssssssssssssss: XFullAccess
              
    - step: status-population
      functionRef:
        name: function-status-transformer
      input:
        apiVersion: function-status-transformer.fn.crossplane.io/v1beta1
        kind: StatusTransformation
        statusConditionHooks:
        - matchers:
          - includeCompositeAsResource: true
            conditions:
            - type: Synced
              status: "False"
              reason: ReconcileError
              message: "(?P<Error>.*)"
          setConditions:
          # Not sure what targetexactly to use but I saw this in the code base. I tried also CompositeAndClaim and still no luck
          - target: Composite
            condition:
              type: CustomReady
              status: "False"
              reason: InternalError
              message: "Error: {{ .Error }}"

    - step: automatically-detect-ready-composed-resources
      functionRef:
        name: function-auto-ready
    
    - step: sequence-creation
      functionRef:
        name: function-sequencer
      input:
        apiVersion: sequencer.fn.crossplane.io/v1beta1
        kind: Input
        rules:
          - sequence:
            - Policy-*
```
### Results

My composite resource have the following status
![image](https://github.com/user-attachments/assets/9a11684e-2fff-4381-b1c8-f5648aec30df)

But my claim have only the following
![image](https://github.com/user-attachments/assets/b0d7d500-247e-4d2d-8e60-8598ace39019)

**Comment by ashishkurian** [comment]
@dalton-hill-0 @negz Can you help me here with identifying my mistake?

**Comment by dalton-hill-0** [comment]
@ashishkurian 

I suspect the pipeline is failing at the `aws-assumerole-policies` step due to the schema error. Since this is hitting a fatal error, the `status-population` step never occurs.

You can try moving the `status-population` step before the `aws-assumerole-policies` step. IIRC that should work.

**Comment by ashishkurian** [comment]
@dalton-hill-0 I moved it up before the aws-assumerole-policies step and still I get the same behavior. The composite status is not updated to the claim. There is no statustransformer update on the composite resource at all.

```yaml
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xawsassumerole.mycompany.com
spec:
  compositeTypeRef:
    apiVersion: mycompany.com/v1alpha1
    kind: XAwsAssumeRole
  environment:
    environmentConfigs:
    - type: Reference
      ref:
        name: iaws-main
    - type: Reference
      ref:
        name: iaws-auto
  mode: Pipeline
  pipeline:
    - step: status-population
      functionRef:
        name: function-status-transformer
      input:
        apiVersion: function-status-transformer.fn.crossplane.io/v1beta1
        kind: StatusTransformation
        statusConditionHooks:
        - matchers:
          - includeCompositeAsResource: true
            type: AnyResourceMatchesAnyCondition
            conditions:
            - type: Synced
              status: "False"
              reason: ReconcileError
              message: "(?P<Error>.*)"
          setConditions:
          # Not sure what targetexactly to use but I saw this in the code base. I tried also CompositeAndClaim and still no luck
          - target: Composite
            condition:
              type: CustomReady
              status: "False"
              reason: InternalError
              message: "Error: {{ .Error }}"

    - step: aws-assumerole-policies
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            {{- $deletionPolicy := "Delete" }}
            {{- $providerConfigRef := "providerconfig-aws" }}
            {{- $claimName := (index .observed.composite.resource.metadata.labels "crossplane.io/claim-name") }}
            ---
            apiVersion: iam.aws.crossplane.io/v1beta1
            kind: Policy
            metadata:
              name: firstpolicy
              labels:
                resource: firstpolicy
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: Policy-FirstPolicy
            spec:
              deletionPolicy: {{$deletionPolicy}}
              providerConfigRef:
                name: {{$providerConfigRef}}
              forProvider:
                name: firstpolicy
                document: |
                  {
                    "Version": "2012-10-17",
                    "Statement": [
                      {
                        "Sid": "EC2DescribeRegion",
                        "Action": "ec2:DescribeRegions",
                        "Effect": "Allow",
                        "Resource": "*"
                      }
                    ]
                  }
                tags:
                  - key: claim-name
                    value: {{$claimName}}
                  - key: created-by
                    value: crossplane
                  - wrongkey: composition-name
                    value: XFullAccess

    - step: automatically-detect-ready-composed-resources
      functionRef:
        name: function-auto-ready
    
    - step: sequence-creation
      functionRef:
        name: function-sequencer
      input:
        apiVersion: sequencer.fn.crossplane.io/v1beta1
        kind: Input
        rules:
          - sequence:
            - Policy-*
```
