### ISSUE TITLE
Overriding Conditions over multiple resources using wildcard

### ISSUE THREAD

**Issue by ashishkurian** [crossplane-contrib/function-status-transformer#37]
### What happened?
My composition have multiple aws iam policy with key name of pattern : Policy-*

I want to propagate the status conditions of these multiple resources but it is not working using the wildcard matching of resources. If I use the exact name of the resource, probably that should work but that means I need to create matchers for each of the policies that I need.

I have matchers created to check the successful creation and failed creation. 

In my first policy, there are no errors but in my second policy I inject error.

I expect that in the claim, I receive the status for the error.

### What I have now

The status of the claim is 
![image](https://github.com/user-attachments/assets/109c2104-344d-49e9-b12a-28a956c52932)

The status of the composite resource is 
![image](https://github.com/user-attachments/assets/e5d71da8-08d2-45d6-a537-82f20ebd4bb1)

### What I expect
As there is error on the second policy, I want the error to be propagated to the claim.

### How can we reproduce it?

I am sharing my k8s manifests below.

```
# composition

---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xawsassumerole.mycompany.com
spec:
  compositeTypeRef:
    apiVersion: mycompany.com/v1alpha1
    kind: XAwsAssumeRole
  environment:
    environmentConfigs:
    - type: Reference
      ref:
        name: iaws-main
    - type: Reference
      ref:
        name: iaws-auto
  mode: Pipeline
  pipeline:
    - step: aws-assumerole-policies
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            {{- $deletionPolicy := "Delete" }}
            {{- $providerConfigRef := "providerconfig-aws" }}
            ---
            apiVersion: iam.aws.crossplane.io/v1beta1
            kind: Policy
            metadata:
              name: firstpolicy
              labels:
                resource: firstpolicy
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: Policy-FirstPolicy
            spec:
              deletionPolicy: {{$deletionPolicy}}
              providerConfigRef:
                name: {{$providerConfigRef}}
              forProvider:
                name: firstpolicy
                document: |
                  {
                    "Version": "2012-10-17",
                    "Statement": [
                      {
                        "Sid": "EC2DescribeRegion",
                        "Action": "ec2:DescribeRegions",
                        "Effect": "Allow",
                        "Resource": "*"
                      }
                    ]
                  }
            ---
            apiVersion: iam.aws.crossplane.io/v1beta1
            kind: Policy
            metadata:
              name: secondpolicy
              labels:
                resource: secondpolicy
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: Policy-SecondPolicy
            spec:
              deletionPolicy: {{$deletionPolicy}}
              providerConfigRef:
                name: {{$providerConfigRef}}
              forProvider:
                name: secondpolicy
                document: |
                  {
                    "Version": "2012-10-17",
                    "Statement": [
                      {
                        "Sid": "EC2DescribeRegion",
                        "Action": "ec2:DescribeRegions",
                        "Effect": "Allow",
                        "Resource": "*",
                        "junk": "junk"
                      }
                    ]
                  }
              
    

    - step: status-population
      functionRef:
        name: function-status-transformer
      input:
        apiVersion: function-status-transformer.fn.crossplane.io/v1beta1
        kind: StatusTransformation
        statusConditionHooks:

        - matchers:
          - resources:
            - name: "Policy-*"
            conditions:
            - type: Ready
              status: "True"
              reason: Available
          setConditions:
          - target: CompositeAndClaim
            condition:
              type: PolicyReady
              status: "True"
              reason: PolicyReady
              message: "Successfully created the policy"
        
        - matchers:
          - resources:
            - name: "Policy-*"
            conditions:
            - type: Synced
              status: "False"
              reason: ReconcileError
              message: "(?P<Error>.*)"
          setConditions:
          - target: CompositeAndClaim
            force: true
            condition:
              type: PolicyReady
              status: "False"
              reason: FailedToCreate
              message: "Error: {{ .Error }}"

    - step: automatically-detect-ready-composed-resources
      functionRef:
        name: function-auto-ready
    
    - step: sequence-creation
      functionRef:
        name: function-sequencer
      input:
        apiVersion: sequencer.fn.crossplane.io/v1beta1
        kind: Input
        rules:
          - sequence:
            - Policy-*


# definition
Not including for brewity
# claim
Not including for brewity
```
-->

**Comment by ashishkurian** [comment]
After reading the documentation better, towards the end I found this section https://github.com/crossplane-contrib/function-status-transformer?tab=readme-ov-file#customizing-matching-behavior. This did the trick for me. I will share the updated composition for reference for other users. 

Probably a good idea to add these as examples.

I will leave it to the maintainers to close this issue/bug. From my side all okay to close this.

```yaml
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xawsassumerole.mycompany.com
spec:
  compositeTypeRef:
    apiVersion: mycompany.com/v1alpha1
    kind: XAwsAssumeRole
  environment:
    environmentConfigs:
    - type: Reference
      ref:
        name: iaws-main
    - type: Reference
      ref:
        name: iaws-auto
  mode: Pipeline
  pipeline:
    - step: aws-assumerole-policies
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            {{- $deletionPolicy := "Delete" }}
            {{- $providerConfigRef := "providerconfig-aws" }}
            ---
            apiVersion: iam.aws.crossplane.io/v1beta1
            kind: Policy
            metadata:
              name: firstpolicy
              labels:
                resource: firstpolicy
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: Policy-FirstPolicy
            spec:
              deletionPolicy: {{$deletionPolicy}}
              providerConfigRef:
                name: {{$providerConfigRef}}
              forProvider:
                name: firstpolicy
                document: |
                  {
                    "Version": "2012-10-17",
                    "Statement": [
                      {
                        "Sid": "EC2DescribeRegion",
                        "Action": "ec2:DescribeRegions",
                        "Effect": "Allow",
                        "Resource": "*"
                      }
                    ]
                  }
            ---
            apiVersion: iam.aws.crossplane.io/v1beta1
            kind: Policy
            metadata:
              name: secondpolicy
              labels:
                resource: secondpolicy
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: Policy-SecondPolicy
            spec:
              deletionPolicy: {{$deletionPolicy}}
              providerConfigRef:
                name: {{$providerConfigRef}}
              forProvider:
                name: secondpolicy
                document: |
                  {
                    "Version": "2012-10-17",
                    "Statement": [
                      {
                        "Sid": "EC2DescribeRegion",
                        "Action": "ec2:DescribeRegions",
                        "Effect": "Allow",
                        "Resource": "*"
                      }
                    ]
                  }
              
    

    - step: status-population
      functionRef:
        name: function-status-transformer
      input:
        apiVersion: function-status-transformer.fn.crossplane.io/v1beta1
        kind: StatusTransformation
        statusConditionHooks:

        - matchers:
          - resources:
            - name: "Policy-*"
            # The change
            type: AllResourcesMatchAllConditions
            conditions:
            - type: Ready
              status: "True"
              reason: Available
            - type: Synced
              status: "True"
              reason: ReconcileSuccess
          setConditions:
          - target: CompositeAndClaim
            condition:
              type: PoliciesReady
              status: "True"
              reason: PoliciesReady
              message: "Successfully created all the policies"
        
        - matchers:
          - resources:
            - name: "Policy-*"
            # The change
            type: AnyResourceMatchesAnyCondition
            conditions:
            - type: Synced
              status: "False"
              reason: ReconcileError
              message: "(?P<Error>.*)"
          setConditions:
          - target: CompositeAndClaim
            force: true
            condition:
              type: PolicyCreate
              status: "False"
              reason: FailedToCreate
              message: "Error in one of the policy: {{ .Error }}"

    - step: automatically-detect-ready-composed-resources
      functionRef:
        name: function-auto-ready
    
    - step: sequence-creation
      functionRef:
        name: function-sequencer
      input:
        apiVersion: sequencer.fn.crossplane.io/v1beta1
        kind: Input
        rules:
          - sequence:
            - Policy-*
```
